apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJiV0Y0YzNOdlltOXNaWFk2WjJod1gxaG9SM2hUU3pOeFdETlFWa1p0VnpOdU5sTXlaMkpGVTFCa05FWjVUekF6VjA1c05BPT0iCiAgICAgICAgfQogICAgfQp9

type: kubernetes.io/dockerconfigjson
