apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
  labels:
    app: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: proxy-service
          image: ghcr.io/maxssobolev/ypr-sprint2/proxy-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
