@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Диаграмма контейнеров

' === Персонажи ===
Person(user, "Пользователь", "Смотрит фильмы через веб, мобильное приложение или Smart TV")
Person(support_agent, "Агент поддержки", "Сотрудник компании")
Person(admin, "Администратор", "Сотрудник компании")
Person(marketing_agent, "Маркетолог", "Сотрудник компании")

' === Системные границы ===
System_Boundary(kc, "Kubernetes Cluster") {
    Container(web, "Веб-приложение", "React", "PWA приложение для пользователей\nHelm Chart: web-app")
    Container(tv, "TV-приложение", "", "TV-приложение для пользователей\nHelm Chart: tv-app")
    Container(admin_web, "Админ-панель", "React", "SPA интерфейс для сотрудников\nHelm Chart: admin-panel")
    
    Container(api_gw, "API Gateway", "Go", "Единая точка входа\nHelm Chart: api-gateway")
    
    Container(user_svc, "User Service", "Go", "Управление пользователями\nHelm Chart: user-service")
    ContainerDb(user_db, "User DB", "PostgreSQL", "Хранение данных пользователей")
    
    Container(content_svc, "Content Service", "Go", "Каталог кинотеатров\nHelm Chart: content-service")
    ContainerDb(content_db, "Content DB", "PostgreSQL", "Данные о кинотеатрах")

    Container(movie_svc, "Movie Metadata Service", "Go", "Метаданные о фильмах \nHelm Chart: movie-service")
    ContainerDb(movie_db, "Movie DB", "PostgreSQL", "Метаданные о фильмах")
    
    Container(interaction_svc, "Interaction Service", "Go", "Оценки, избранное, история\nHelm Chart: interaction-service")
    ContainerDb(interaction_db, "Interaction DB", "MongoDB", "Пользовательские взаимодействия")
    
    Container(billing_svc, "Billing Service", "Go", "Подписки и платежи\nHelm Chart: billing-service")
    ContainerDb(billing_db, "Billing DB", "PostgreSQL", "Данные о подписках")
    
    Container(support_svc, "Support Service", "Go", "Тикеты и обратная связь\nHelm Chart: support-service")
    ContainerDb(support_db, "Support DB", "PostgreSQL", "База тикетов")
    
    Container(analytics_svc, "Analytics Service", "Go", "Сбор и анализ статистики\nHelm Chart: analytics-service")
    ContainerDb(analytics_db, "Analytics DB", "ClickHouse", "Аналитические данные")
    
    ContainerQueue(rabbitmq, "Message Broker", "RabbitMQ", "Асинхронные события\nHelm Chart: rabbitmq")
}


System_Ext(payment, "Платежная система", "Внешний платежный шлюз")
System_Ext(recommendation, "Система рекомендаций", "Внешняя рекомендательная система")
System_Ext(s3, "Облачное хранилище", "S3")
System_Ext(cinema1, "Кинотеатр 1", "Партнерский кинотеатр")
System_Ext(cinema2, "Кинотеатр 2", "Партнерский кинотеатр")


Rel(user, web, "Использует", "HTTPS")
Rel(user, tv, "Использует")
Rel(support_agent, admin_web, "Работает с тикетами", "HTTPS")
Rel(admin, admin_web, "Администрирует", "HTTPS")
Rel(marketing_agent, admin_web, "Анализирует данные", "HTTPS")

Rel(web, api_gw, "API Calls", "HTTPS/REST")
Rel(tv, api_gw, "API Calls", "HTTPS/REST")
Rel(admin_web, api_gw, "API Calls", "HTTPS/REST")

Rel(api_gw, user_svc, "gRPC")
Rel(api_gw, content_svc, "gRPC")
Rel(api_gw, movie_svc, "gRPC")
Rel(api_gw, interaction_svc, "gRPC")
Rel(api_gw, billing_svc, "gRPC")
Rel(api_gw, support_svc, "gRPC")
Rel(api_gw, analytics_svc, "gRPC")
Rel(api_gw, recommendation, "HTTP", "Получение рекомендаций")

Rel(user_svc, user_db, "SQL")
Rel(content_svc, content_db, "SQL")
Rel(movie_svc, movie_db, "SQL")
Rel(interaction_svc, interaction_db, "NoSQL")
Rel(billing_svc, billing_db, "SQL")
Rel(analytics_svc, movie_svc, "gRPC", "Запрос метаданных фильмов")
Rel(interaction_svc, movie_svc, "gRPC", "Получение данных о фильме")
Rel(content_svc, movie_svc, "gRPC", "Получение информации о фильмах")
Rel(support_svc, support_db, "SQL")
Rel(analytics_svc, analytics_db, "SQL")

Rel(interaction_svc, rabbitmq, "AMQP", "События: оценки/просмотры")
Rel(content_svc, rabbitmq, "AMQP", "События: новый контент")
Rel(rabbitmq, recommendation, "AMQP", "События для обработки")

Rel(billing_svc, payment, "HTTPS", "Payment API")

Rel(user_svc, content_svc, "gRPC", "Запрос данных пользователя")
Rel(billing_svc, user_svc, "gRPC", "Проверка подписки")
Rel(analytics_svc, content_svc, "HTTP", "Запрос метаданных")

Rel(movie_svc, s3, "HTTPS", "Загрузка/получение медиа-контента")
Rel(content_svc, cinema1, "API calls", "Синхронизация данных")
Rel(content_svc, cinema2, "API calls", "Синхронизация данных")

' Helm чарты
AddRelTag("helm")
Rel(web, web, "Helm Chart", "web-app")
Rel(tv, tv, "Helm Chart", "tv-app")
Rel(admin_web, admin_web, "Helm Chart", "admin-panel")
Rel(api_gw, api_gw, "Helm Chart", "api-gateway")
Rel(user_svc, user_svc, "Helm Chart", "user-service")
Rel(content_svc, content_svc, "Helm Chart", "content-service")
Rel(movie_svc, movie_svc, "Helm Chart", "movie-service")
Rel(interaction_svc, interaction_svc, "Helm Chart", "interaction-service")
Rel(billing_svc, billing_svc, "Helm Chart", "billing-service")
Rel(support_svc, support_svc, "Helm Chart", "support-service")
Rel(analytics_svc, analytics_svc, "Helm Chart", "analytics-service")
Rel(rabbitmq, rabbitmq, "Helm Chart", "rabbitmq")

@enduml